apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.service.loadBalancerType "classic" }}
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    {{- else if eq .Values.service.loadBalancerType "nlb" }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    {{- end }}
    {{- with .Values.service.annotations }}
{{ toYaml . | nindent 4 }}
    {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web-app.selectorLabels" . | nindent 4 }}
